# Generated by Django 5.2.13 on 2026-04-12 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('actor_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('result', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='success', max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['trace_id', 'created_at'], name='idx_audit_trace_time'), models.Index(fields=['action', 'created_at'], name='idx_audit_action_time')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public'), ('common', 'Common')], default='private', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skill',
                'indexes': [models.Index(fields=['owner_id', 'visibility', 'status'], name='idx_skill_query')],
                'constraints': [models.UniqueConstraint(fields=('owner_id', 'name'), name='uq_skill_owner_name')],
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('artifact_uri', models.CharField(max_length=512)),
                ('artifact_sha256', models.CharField(max_length=128)),
                ('signature', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_version',
            },
        ),
        migrations.CreateModel(
            name='SessionSkillBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=64)),
                ('sandbox_id', models.CharField(blank=True, default='', max_length=128)),
                ('mounted_path', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mounted', 'Mounted'), ('failed', 'Failed'), ('unmounted', 'Unmounted')], default='pending', max_length=16)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='skills.skillversion')),
            ],
            options={
                'db_table': 'session_skill_binding',
            },
        ),
        migrations.CreateModel(
            name='SkillPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=16)),
                ('subject_id', models.CharField(max_length=128)),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_permission',
                'constraints': [models.UniqueConstraint(fields=('skill', 'subject_type', 'subject_id'), name='uq_skill_permission_subject')],
            },
        ),
        migrations.AddIndex(
            model_name='skillversion',
            index=models.Index(fields=['skill', 'is_active'], name='idx_skill_active'),
        ),
        migrations.AddConstraint(
            model_name='skillversion',
            constraint=models.UniqueConstraint(fields=('skill', 'version'), name='uq_skill_version'),
        ),
        migrations.AddIndex(
            model_name='sessionskillbinding',
            index=models.Index(fields=['session_id', 'user_id'], name='idx_binding_session_user'),
        ),
        migrations.AddIndex(
            model_name='sessionskillbinding',
            index=models.Index(fields=['status', 'expire_at'], name='idx_binding_status_expire'),
        ),
    ]
